In [1]:
##### 5.2 핵심 기능 #####
# Series나 DataFrame에 저장된 데이터를 다루는 기본적인 방벙

In [1]:
##### 5.2.1 재색인 #####
# reindex : 새로운 색인에 맞도록 객체를 새로 생성한다.

import pandas as pd

obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])

In [4]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [5]:
# 시계열같은 순차적인 데이터를 재색인할 때 값을 보간하거나 채워넣어야하는 경우 method 옵션을 사용한다.
# ffill 메서드를 이용해 누락된 값을 직전의 값으로 채워넣을 수 있다.

obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])

In [6]:
obj3

0      blue
2    purple
4    yellow
dtype: object

In [7]:
obj3.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [2]:
# Dataframe에 대한 reindex는 로우(색인), 컬럼 또는 둘 다 변경가능하다.
# 그냥 순서만 전달하면 로우가 재색인된다.

import numpy as np

frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                    index = ['a', 'c', 'd',],
                    columns = ['Ohio', 'Texas', 'California'])

In [22]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [17]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])

In [18]:
frame2

Ohio   Texas  California
a   0.0     1.0         2.0
b   NaN     NaN         NaN
c   3.0     4.0         5.0
d   6.0     7.0         8.0

In [23]:
# 컬럼은 columns 예약어를 사용해 재색인 할 수 있다.

states = ['Texas', 'Utah', 'California']

In [24]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [26]:
# 재색인은 loc을 이용해 라벨로 색인하면 좀 더 간결하게 할 수 있다.

frame.loc[['a', 'b', 'c', 'd'], states]

c:\users\lg\appdata\local\programs\python\python37-32\lib\site-packages\pandas\core\indexing.py:1418: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [27]:
##### 5.2.2 하나의 로우나 컬럼 삭제하기 #####

obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [28]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [29]:
new_obj = obj.drop('c')

In [30]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [31]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [34]:
# DataFrame에서는 로우와 컬럼 모두에서 값을 삭제할 수 있다.

data = pd.DataFrame(np.arange(16).reshape((4,4)),
                   index=['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns=['one', 'two', 'three', 'four'])

In [35]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [36]:
# drop 함수에 인자로 로우 이름을 넘기면 해당 로우 (axis 0)의 값을 모두 삭제한다.

data.drop(['Colorado', 'Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [37]:
# 컬럼의 값을 삭제할 때는 axis=1 또는 axis='columns'를 인자로 넘겨주면 된다.

data.drop('two', axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [38]:
data.drop(['two', 'four'], axis = 'columns')

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [39]:
# drop 함수처럼 Series나 DataFrame의 크기나 형태를 변경하는 함수는 새로운 객체를 반환하는 대신 원본 객체를 변경한다.
# inplace 옵션을 사용하는 경우 버려지는 값을 모두 삭제하므로 주의해서 사용하자.

obj.drop('c', inplace=True)

In [40]:
obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [41]:
##### 5.2.3 색인하기, 선택하기, 거르기 #####
# Series의 색인(obj[..])은 numpy 배열의 색인과 유사하게 동작하지만 정수가 아니어도 된다는 점이 다르다.

obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])

In [42]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [43]:
obj['b']

1.0

In [44]:
obj[1]

1.0

In [45]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [46]:
obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [48]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [49]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [50]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [51]:
obj['b':'c'] = 5

In [52]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [53]:
# 색인으로 DataFrame에서 하나 이상의 컬럼 값을 가져올 수 있다.

data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                   index = ['Ohio', 'Colorado', 'Utah', 'New York'],
                   columns = ['one', 'two', 'three', 'four'])

In [54]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [55]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [56]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [57]:
# 슬라이싱으로 로우를 선택하거나 불리언 배열로 로우를 선택할 수 있다.

data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [59]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [61]:
# 스칼라 비교를 이용해 생성된 불리언 DataFrame을 사용해서 값 선택

data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [62]:
data[data < 5] = 0

In [63]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [64]:
## loc과 iloc으로 선택하기
# DataFrame의 로우에 대해 라벨로 색인하는 방법으로 특수한 색인 필드인 loc과 iloc을 소개한다.
# loc : 축 이름을 선택 / iloc : 정수 색인으로 선택

data.loc['Colorado', ['two', 'three']]

two      5
three    6
Name: Colorado, dtype: int32

In [65]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [66]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [67]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [68]:
# 두 함수는 슬라이스도 지원할 뿐더러 단일 라벨이나 라벨 리스트도 지원한다.

data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [69]:
data.iloc[:, :3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [70]:
##### 5.2.4 정수 색인 #####

In [3]:
ser = pd.Series(np.arange(3, ))

In [4]:
ser

0    0
1    1
2    2
dtype: int32

In [6]:
# pandas는 라벨 색인을 찾는 데 실패하여 정수 색인으로 값을 찾는다.
# 라벨 색인이 0, 1, 2를 포함하는 경우
# 사용자가 라벨 색인으로 선택하려는 것인지 정수 색인으로 선택하려는 것인지 추측하기 쉽지 않다.
ser[-1]

KeyError: -1

In [7]:
# 반면 정수 기반의 색인을 사용하지 않으면 이런 모호함은 사라진다.

ser2 = pd.Series(np.arange(3, ), index = ['a', 'b', 'c'])

In [8]:
ser2[-1]

2

In [9]:
ser2

a    0
b    1
c    2
dtype: int32

In [10]:
# 일관성 유지를 위해 정숫값을 담고 있는 축 색인이 있다면 우선적으로 라벨을 먼저 찾아보도록 구현되어있다.

ser[:1]

0    0
dtype: int32

In [11]:
# 좀 더 세밀하게 사용하고싶은 경우

ser.loc[:1] # 라벨

0    0
1    1
dtype: int32

In [12]:
ser.iloc[:1] # 정수색인

0    0
dtype: int32

In [13]:
##### 5.2.5 산술 연산과 데이터 정렬 #####

In [14]:
# 다른 색인을 가지고 있는 객체 데이터 간의 산술연산

s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index = ['a', 'c', 'd', 'e'])

In [15]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index = ['a', 'c', 'e', 'f', 'g'])

In [16]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [17]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [18]:
# 서로 겹치는 색인이 없는 경우 NA 값이 된다.

s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [19]:
# DataFrame의 경우 정렬은 로우와 컬럼 모두에 적용된다.

df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns = list('bcd'), index = ['Ohio', 'Texas', 'Colorado'])

In [20]:
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [21]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [22]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [23]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [24]:
# 공통되는 컬럼 라벨이나 로우 라벨이 없는 DataFrame을 더하면 결과에 아무것도 나타나지 않을 것이다.

df1 = pd.DataFrame({'A': [1, 2]})

In [25]:
df2 = pd.DataFrame({'B': [3, 4]})

In [26]:
df1

A
0  1
1  2

In [27]:
df2

B
0  3
1  4

In [28]:
df1 - df2

A   B
0 NaN NaN
1 NaN NaN

In [29]:
## 산술연산 메서드에 채워 넣을 값 지정하기
# 서로 다른 색인을 가지는 객체간 산술 연산에서 존재하지 않는 축의 값을 특수한값으로 지정하기

df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns = list('abcd'))

In [30]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns = list('abcde'))

In [31]:
df2.loc[1, 'b'] = np.nan

In [32]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [33]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [34]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [35]:
# df1에 add 메서드를 사용하기, df2와 fill_value 값을 인자로 전달한다.

df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [36]:
# 각 산술연산 메서드는 r로 시작하는 계산 인자를 뒤집어 계산하는 짝꿍 메서드를 가진다.

1 / df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [37]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [38]:
# Series나 DataFrame을 재색인할 때도 fill_value를 지정할 수 있다.

df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [39]:
## DataFrame과 Series 간의 연산

In [40]:
# 2차원 배열과 그 배열의 한 로우의 차이에 대해 생각할 수 있는 예제
arr = np.arange(12.).reshape((3, 4))

In [41]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [42]:
arr[0]

array([0., 1., 2., 3.])

In [43]:
arr - arr[0]  # 브로드캐스팅

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [44]:
# DataFrame과 Series 간의 연산

frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [45]:
series = frame.iloc[0]

In [46]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [47]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [49]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [50]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [52]:
# 색인값을 DataFrame의 컬럼이나 Series에서 찾을 수 없으면 그 객체는 재색인된다.

series2 = pd.Series(range(3), index = ['b', 'e', 'f'])

In [53]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [54]:
# 로우에 대한 연산을 수행하고 싶다면 산술 연산 메서드를 사용하면 된다.

series3 = frame['d']

In [55]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [56]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [57]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [58]:
# 인자로 넘기는 axis 값은 연산을 적용할 축 번호다.
# axis = 'index'나  axis = 0은 DataFrame의 로우를 따라 연산을 수행하라는 의미이다.

In [59]:
##### 5.2.6 함수 적용과 매핑 #####
# pandas 객체에도 Numpy의 유니버설 함수 (배열의 각 원소에 적용되는 메서드)를 적용할 수 있다.

frame = pd.DataFrame(np.random.randn(4, 3), columns = list('bde'), index = ['Utah', 'Ohio', 'Texas', 'Oregon'])

In [60]:
frame

b         d         e
Utah    0.138787  1.352384  0.695282
Ohio    1.329274 -1.270972 -0.604705
Texas  -0.171448 -1.121958 -1.738280
Oregon -2.257326  1.041647 -0.083306

In [61]:
np.abs(frame)

b         d         e
Utah    0.138787  1.352384  0.695282
Ohio    1.329274  1.270972  0.604705
Texas   0.171448  1.121958  1.738280
Oregon  2.257326  1.041647  0.083306

In [62]:
f = lambda x: x.max() - x.min()

In [63]:
frame.apply(f)

b    3.586601
d    2.623356
e    2.433562
dtype: float64

In [64]:
# 배열에 대한 일반적인 통계(sum이나 mean같은)는 DataFrame의 메서드로 존재하므로 apply 메서드를 사용할 필요없다.
# apply 메서드에 전달된 함수는 스칼라값을 반환할 필요가 없다.
# 여러 값을 가진 Series를 반환해도 된다.

def f(x):
    return pd.Series([x.min(), x.max()], index = ['min', 'max'])

In [65]:
frame.apply(f)

b         d         e
min -2.257326 -1.270972 -1.738280
max  1.329274  1.352384  0.695282

In [66]:
# 배열의 각 원소에 적용되는 파이썬의 함수를 사용할 수도 있다.
# frame 객체에서 실숫값을 문자열 포맷으로 변환하고 싶다면 applymap을 이용해서 다음과 같이 할 수 있다.

format = lambda x: '%.2f' % x

In [67]:
frame.applymap(format)

b      d      e
Utah     0.14   1.35   0.70
Ohio     1.33  -1.27  -0.60
Texas   -0.17  -1.12  -1.74
Oregon  -2.26   1.04  -0.08

In [68]:
# Series는 각 원소에 적용할 함수를 지정하기 위한 map 메서드를 가지고 있기 때문이다.

frame['e'].map(format)

Utah       0.70
Ohio      -0.60
Texas     -1.74
Oregon    -0.08
Name: e, dtype: object

In [69]:
##### 5.2.7 정렬과 순위 #####