In [1]:
##### 4. Numpy 기본: 배열과 벡터 계산 #####

In [2]:
# Numpy는 Numerical python의 줄임말로 산술 계산에 사용하는 패키지 중 하나이다.
# 과학 계산을 위한 대부분의 패키지는 Numpy 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용한다.

In [3]:
# 백만개의 정수를 저장하는 numpy 배열과 파이썬 리스트를 비교해보자

import numpy as np

In [4]:
my_arr = np.arange(1000000)

In [5]:
my_list = list(range(1000000))

In [6]:
# 이제 각 배열과 리스트 원소에 2를 곱해보자.

In [7]:
%time for _ in range(10): my_arr2 = my_arr * 2

Wall time: 33.5 ms


In [8]:
%time for _ in range(10): my_list2 = [x * 2 for x in my_list]

Wall time: 1.47 s


In [9]:
# numpy를 사용한 코드가 순수 파이썬으로 작성한 코드보다 10 ~ 100 이상 빠르고 메모리도 더 적게 사용한다.

In [10]:
##### 4.1 Numpy ndarray : 다차원 배열 객체 #####
#ndarray : 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조

In [11]:
# 작은 배열을 만들고 산술연산 해보기

import numpy as np

In [12]:
data = np.random.randn(2, 3)

In [13]:
data

array([[-0.26890773,  1.20480488,  0.38887775],
       [-1.43834618,  1.20379592,  1.25212519]])

In [14]:
data * 10

array([[ -2.6890773 ,  12.04804877,   3.88877747],
       [-14.38346183,  12.0379592 ,  12.5212519 ]])

In [15]:
data + data

array([[-0.53781546,  2.40960975,  0.77775549],
       [-2.87669237,  2.40759184,  2.50425038]])

In [17]:
# ndarray는 같은 종류의 데이터를 담을 수 있는 포괄적인 다차원 배열이다.
# ndarray의 모든 원소는 같은 자료형이어야 한다.
# 모든 배열은 각 차원의 크기를 알려주는 shape 이라는 튜플과 배열에 저장된 자료형을 알려주는 dtype이라는 객체를 가지고 있다.

data.shape

(2, 3)

In [18]:
data.dtype

dtype('float64')

In [19]:
##### 4.1.1 ndarray 생성하기 #####
# ndarray : 배열을 생성하는 가장 쉬운 방법
# 순차적인 객체(리스트 등)를 넘겨받고, 그 데이터가 들어있는 새로운 numpy 배열 생성

data1 = [6, 7.5, 8, 0, 1]

In [20]:
arr1 = np.array(data1)

In [21]:
arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [22]:
# 같은 길이를 가지는 리스트를 내포하고 있는 순차 데이터는 다차원 배열로 변환 가능

data2 = [[1,2,3,4],[5,6,7,8]]

In [23]:
arr2 = np.array(data2)

In [24]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
# data2는 리스트를 담고 있는 리스트이므로 arr2는 2차원 형태로 생성된다.
# ndim과 shape 속성을 검사해서 이를 확인할 수 있다.

arr2.ndim

2

In [26]:
arr2.shape

(2, 4)

In [27]:
# np.array는 생성될 때 적절한 자료형을 추론한다.

arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [29]:
# zeros, ones는 주어진 길이나 모양에 각각 0과 1이 들어있는 배열 생성

np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [33]:
# arange는 파이썬 range함수의 배열 버전이다.

np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
##### 4.1.2 ndarray와 dtype #####
# dtype : ndarray가 메모리에 있는 특정데이터를 해석하기위해 필요한 정도(메타데이터)를 담고있는 특수힌 객체

arr1 = np.array([1, 2, 3], dtype=np.float64)

In [37]:
arr2 = np.array([1, 2, 3], dtype=np.int32)

In [38]:
arr1.dtype

dtype('float64')

In [39]:
arr2.dtype

dtype('int32')

In [40]:
# ndarray의 astype 메서드를 사용해 배열의 dtype을 다른 형으로 명시적으로 변환(캐스팅) 가능하다 .

arr = np.array([1, 2, 3, 4, 5])

In [41]:
arr.dtype

dtype('int32')

In [43]:
float_arr = arr.astype(np.float64)

In [46]:
float_arr.dtype

dtype('float64')

In [51]:
# 정수형이 부동소수점으로 변환했다.

float_arr

array([1., 2., 3., 4., 5.])

In [52]:
# 만약 부동소수점수를 정수형 dtype으로 변환하는 소수점 아래 자리는 버려진다.

arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])

In [53]:
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [54]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10])

In [55]:
# 숫자 형식의 문자열을 담고 있는 배열이 있다면 astype를 사용하여 숫자로 변환할 수 있다.

numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)

In [56]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

In [57]:
# 만일 행변환이 실패하면 ValueError 예외가 발생한다.
# 다른 dtype 속성을 이용하는 것도 가능하다.

int_array = np.arange(10)

In [59]:
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)

In [60]:
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [61]:
# dtype으로 사용할 수 있는 축약 코드도 있다.

empty_uint32 = np.empty(8, dtype='u4')

In [63]:
empty_uint32

array([         0, 1075314688,          0, 1075707904,          0,
       1075838976,          0, 1072693248], dtype=uint32)

In [65]:
##### 4.1.3 Numpy 배열의 산술 연산 #####
# 배열은 for문을 이용하지 않고 데이터를 일괄처리 할 수 있다. (벡터화)
# 같은 크기의 배열 간 산술 연산은 배열의 각 원소 단위로 적용된다.

arr = np.array([[1., 2., 3.], [4., 5., 6.]])

In [66]:
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [67]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [68]:
arr - arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [70]:
arr ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [71]:
# 같은 크기를 가지는 배열 간 비교 연산은 불리언 배열을 반환한다.

arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])

In [72]:
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [73]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [74]:
##### 4.1.4 색인과 슬라이싱 기초 #####
# 데이터의 부분집합이나 개별 요소를 선택하기 위한 방법
# 1차원 배열 방법은 표면적으로 파이썬의 리스트와 유사하게 작동한다.

arr = np.arange(10)

In [75]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [76]:
arr[5]

5

In [77]:
arr[5:8]

array([5, 6, 7])

In [80]:
# 이렇게 하면 12가 arr의 5:8 자리값에 들어가게 된다.

arr[5:8] = 12

In [81]:
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [82]:
# 리스트와의 차이점은 배열조각은 원본 배열의 뷰라는 점이다.
# 즉, 데이터는 복사되지 않고 뷰에 대한 변경은 그대로 원본 배열에 반영된다.

In [83]:
# 예제로 먼저 arr배열의 슬라이스를 생성해보자.

arr_slice = arr[5:8]

In [84]:
arr_slice

array([12, 12, 12])

In [87]:
# arr_slice의 값을 변경하면 원래 배열인 arr의 값도 바뀌어있다.

arr_slice[1] = 12345

In [88]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [89]:
# 단순히 [:]로 슬라이스를 하면 배열의 모든 값을 할당한다.

arr_slice[:] = 64

In [90]:
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [91]:
# 2차원 배열에서 각 색인에 해당하는 요소는 스칼라값이 아니라 1차원 배열이다.

arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [93]:
arr2d[2]

array([7, 8, 9])

In [94]:
# 따라서 개별 요소는 재귀적으로 접근해야한다.
# 콤마로 구분된 색인 리스트를 넘겨도 된다.

arr2d[0][2]

3

In [95]:
arr2d[0, 2]

3

In [96]:
# 다차원 배열에서 마지막 색인을 생략하면 반환되는 객체는 상위 차원의 데이터를 포함하고 있는 한 차원 낮은 ndarray가 된다.

In [97]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9],[10, 11, 12]]])

In [98]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [99]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [100]:
old_values = arr3d[0].copy()

In [101]:
old_values

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
# arr3d[0]에는 스칼라값과 배열 모두 대입할 수 있다.

arr3d[0] = 42

In [104]:
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [105]:
arr3d[0] = old_values

In [106]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [109]:
# 이것은 (1, 0)으로 색인되는 1차원 배열과 그 값을 반환한다.

arr3d[1, 0]

array([7, 8, 9])

In [110]:
# 위 표현은 다음처럼 두 번에 걸쳐 인덱싱한 결과와 동일하다.

x = arr3d[1]

In [111]:
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [112]:
x[0]

array([7, 8, 9])

In [113]:
## 슬라이스로 선택하기
# 파이썬의 리스트 같은 1차원 객체처럼 ndarray는 익숙한 문법으로 슬라이싱 할 수 있다.

arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [114]:
arr[1:6]

array([ 1,  2,  3,  4, 64])

In [115]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [116]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [118]:
arr2d[:2, 1:]

array([[2, 3],
       [5, 6]])

In [119]:
# 정수 색인과 슬라이스를 함께 사용하여 한 차원 낮은 슬라이스를 얻을 수있다.

arr2d[1, :2]

array([4, 5])

In [120]:
arr2d[:2, 2]

array([3, 6])

In [122]:
# 콜론만 사용하면 전체 축을 선택한다는 의미

arr2d[:, :1]

array([[1],
       [4],
       [7]])

In [123]:
arr2d[:2, 1:] = 0

In [124]:
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [125]:
##### 4.1.5 불리언값으로 선택하기 #####

In [126]:
# 중복된 이름이 포함된 배열이 있다고 하자.
# numpy.random 모듈에 있는 randn 함수를 사용해서 임의의 표준 정규분포데이터를 생성하자.

names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

In [127]:
data = np.random.randn(7, 4)

In [128]:
names

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [129]:
data

array([[-0.26113138,  1.07712593,  0.77697606, -0.32711359],
       [-0.93666183, -1.56548437,  1.04167913,  0.60639657],
       [ 0.21073793, -0.93430479, -0.56143843, -1.43209257],
       [-0.36206241, -0.7539663 , -0.39157172,  0.03425067],
       [-1.59221866, -2.07756404, -1.09961496,  0.21051611],
       [ 0.04410816, -0.31102637,  0.2574838 , -0.22063864],
       [-0.29710036, -1.59131901,  0.14805698, -1.28428734]])

In [130]:
# 각각의 이름은 data배열의 각 로우에 대응한다고 가정하자.
# 만약 전체 로우에서 'Bob'과 같은 이름을 선택하려면
# 산술 연산과 마찬가지로 배열에 대한 비교 연산도 벡터화되므로 names를 'Bob'문자열과 비교하면 불리언 배열을 반환한다.

In [131]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [132]:
# 불리언 배열은 색인도 가능한데, 반드시 색인하려는 축의 길이와 동일한 길이를 가져야한다.

data[names == 'Bob']

array([[-0.26113138,  1.07712593,  0.77697606, -0.32711359],
       [-0.36206241, -0.7539663 , -0.39157172,  0.03425067]])

In [135]:
# names == 'Bob'인 로우에서 2:컬럼을 선택했다.

data[names == 'Bob', 2:]

array([[ 0.77697606, -0.32711359],
       [-0.39157172,  0.03425067]])

In [136]:
# 'Bob'이 아닌 요소

names != 'Bob'

array([False,  True,  True, False,  True,  True,  True])

In [137]:
data[~(names == 'Bob')]

array([[-0.93666183, -1.56548437,  1.04167913,  0.60639657],
       [ 0.21073793, -0.93430479, -0.56143843, -1.43209257],
       [-1.59221866, -2.07756404, -1.09961496,  0.21051611],
       [ 0.04410816, -0.31102637,  0.2574838 , -0.22063864],
       [-0.29710036, -1.59131901,  0.14805698, -1.28428734]])

In [138]:
# ~ 연산자는 일반적인 조건을 반대로 쓰고 싶을 때 유용하다.

cond = names == 'Bob'

In [139]:
data[~cond]

array([[-0.93666183, -1.56548437,  1.04167913,  0.60639657],
       [ 0.21073793, -0.93430479, -0.56143843, -1.43209257],
       [-1.59221866, -2.07756404, -1.09961496,  0.21051611],
       [ 0.04410816, -0.31102637,  0.2574838 , -0.22063864],
       [-0.29710036, -1.59131901,  0.14805698, -1.28428734]])

In [140]:
mask = (names == 'Bob') | (names == 'Will')

In [141]:
mask

array([ True, False,  True,  True,  True, False, False])

In [142]:
data[mask]

array([[-0.26113138,  1.07712593,  0.77697606, -0.32711359],
       [ 0.21073793, -0.93430479, -0.56143843, -1.43209257],
       [-0.36206241, -0.7539663 , -0.39157172,  0.03425067],
       [-1.59221866, -2.07756404, -1.09961496,  0.21051611]])

In [143]:
# 배열에 불리언 색인을 이용해서 데이터를 선택하면 반환되는 배열의 내용이 바뀌지 않더라도 항상 데이터 복사가 발생한다.

In [144]:
data[data < 0] = 0

In [145]:
data

array([[0.        , 1.07712593, 0.77697606, 0.        ],
       [0.        , 0.        , 1.04167913, 0.60639657],
       [0.21073793, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.03425067],
       [0.        , 0.        , 0.        , 0.21051611],
       [0.04410816, 0.        , 0.2574838 , 0.        ],
       [0.        , 0.        , 0.14805698, 0.        ]])

In [146]:
# 1차원 불리언 배열을 사용해서 전체 로우나 컬럼을 선택하는 것은 쉽게 할 수 있다.

data[names != 'Joe'] = 7

In [147]:
data

array([[7.        , 7.        , 7.        , 7.        ],
       [0.        , 0.        , 1.04167913, 0.60639657],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [7.        , 7.        , 7.        , 7.        ],
       [0.04410816, 0.        , 0.2574838 , 0.        ],
       [0.        , 0.        , 0.14805698, 0.        ]])

In [150]:
##### 4.1.6 팬시 색인 #####
# 팬시 색인 : 정수배열을 사용한 색인을 설명하기 위해 numpy에서 차용한 단어

In [151]:
arr = np.empty((8, 4))

In [152]:
for i in range(8):
    arr[i] = i

In [153]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [155]:
# 특정한 순서의 로우 선택

arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [156]:
arr[[-3, -5, -7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [157]:
# 다차원 색인 배열 넘기기
# 각각의 색인 튜플에 대응하는 1차원 배열이 선택된다.

arr = np.arange(32).reshape((8, 4))

In [158]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [159]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]

array([ 4, 23, 29, 10])

In [160]:
# 행과 열에 대응하는 사각형 모양의 값이 선택되길 기대하는 경우

arr[[1, 5, 7, 2]][:, [0, 3, 1, 2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [161]:
##### 4.1.7 배열 전치와 축 바꾸기 #####
# 배열 전치는 데이터를 복사하지 않고 데이터의 모양이 바뀐 뷰를 반환하는 기능이다.

In [162]:
# ndarray는 transpose 메서드와 T라는 이름의 특수한 속성을 가지고 있다.

arr = np.arange(15).reshape((3, 5))

In [163]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [164]:
arr.T

array([[ 0,  5, 10],
       [ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14]])

In [165]:
arr = np.random.randn(6, 3)

In [166]:
arr

array([[ 0.03207385, -0.39751773,  0.60636063],
       [ 2.21572545,  0.78261281,  0.59184607],
       [-1.48351573, -1.52613841, -0.52273359],
       [ 0.11550439, -0.69533436, -0.22841079],
       [-0.11809982,  0.76328068, -1.82962993],
       [ 0.46913136, -0.94045135, -1.16550183]])

In [167]:
np.dot(arr.T, arr)

array([[7.35865999, 3.37370284, 1.74922328],
       [3.37370284, 5.05013764, 0.8783095 ],
       [1.74922328, 0.8783095 , 5.74931707]])

In [168]:
# 다차원 배열의 경우 transpose 메서드는 튜플로 축 번호를 받아 치환한다.
# 첫번째와 두번째의 축 순서가 바뀌고 마지막 축은 그대로 이다.

arr = np.arange(16).reshape((2, 2, 4))

In [170]:
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [171]:
arr.transpose((1, 0, 2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [174]:
# swapaxes 메서드 : 두 개의 축 번호를 받아 배열을 뒤바꾼다.

arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [173]:
arr.swapaxes(1, 2)

array([[[ 0,  4],
        [ 1,  5],
        [ 2,  6],
        [ 3,  7]],

       [[ 8, 12],
        [ 9, 13],
        [10, 14],
        [11, 15]]])