In [1]:
##### 5 pandas 시작하기 #####

In [21]:
import pandas as pd

In [22]:
from pandas import Series, DataFrame

In [23]:
##### 5.1 pandas 자료구조 소개 #####
##### 5.1.1 Series #####
# Series는 일련의 객체를 담을 수 있는 1차원 배열 같은 자료구조이다.
# 색인이라고 하는 배열의 데이터와 연관된 이름을 가지고 있다.
# 가장 간단한 Series 객체는 배열 데이터로 부터 생성할 수 있다.

obj = pd.Series([4, 7, -5, 3])

In [24]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [25]:
# Series 객체의 문자열 표현은 왼쪽에 색인을 보여주고 오른쪽에 해당 색인의 값을 보여준다.
# 위 예제에서는 색인을 지정하지않았으므로 시본 색인인 정수 0에서 N-1을 표시하였다.

In [26]:
# Series의 배열과 색인 객체는 각각 values와 index 속성을 통해 얻을 수 있다.

obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [27]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [28]:
# 색인 지정

obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])

In [29]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [30]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [31]:
# numpy 배열과 비교하자면, 단일 값을 선택하거나 여러 값을 선택할 때 색인으로 라벨을 사용할 수 있다.

obj2['a']

-5

In [32]:
obj2['d']=6

In [33]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [34]:
# 불리언 배열을 사용해 값을 걸러내거나, 산술계산, 수학함수적용 등에도 색인-값 연결이 유지된다.

obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [35]:
obj2*2

d    12
b    14
a   -10
c     6
dtype: int64

In [36]:
import numpy as np

np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [37]:
# Sereis객체는 파이썬의 사전형을 인자로 받아야하는 많은 함수에서 사전형을 대체하여 사용할 수 있다.

'b' in obj2

True

In [38]:
'e' in obj2

False

In [39]:
# 파이썬 사전형에 데이터를 저장해야 한다면 파이썬 사전 객체로부터 Series 객체를 생성할 수 있다.

sdata = {'Ohio':35000, 'Texas':71000, 'Oregon':16000, 'Utah':5000}

In [40]:
obj3 = pd.Series(sdata)

In [41]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [42]:
# 사전 객체로 Series 객체를 생성하면 키-값 순으로 들어간다.
# 색인을 직접 지정하면 원하는 순서대로 넘길 수 있다.

states = ['California', 'Ohio', 'Oregon', 'Texas']

In [43]:
obj4 = pd.Series(sdata, index=states)

In [44]:
# California와 같이 찾을 수 없는 값은 NaN으로 표시된다.

obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [45]:
# NA 값 찾기

pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [46]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [47]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [48]:
# 산술연산에서 색인과 라벨로 자동정렬

obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [49]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [50]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [51]:
# Sereis의 객체와 색인은 name 속성이 있다.

obj4.name = 'population'

In [52]:
obj4.index.name = 'state'

In [53]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [54]:
# Series 색인은 대입하여 변경할 수 있다.

obj

0    4
1    7
2   -5
3    3
dtype: int64

In [55]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']

In [56]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [57]:
# dataframe 객체를 생성하는 가장 흔한 방법은 리스트에 담긴 사전을 이용하거나 Numpy 배열을 이용하는 것이다.

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
       'year': [2000, 2001, 2002, 2001, 2002, 2003],
       'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

In [58]:
frame = pd.DataFrame(data)

In [59]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [60]:
# 상위 5개 데이터만 출력
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [61]:
# 열 순서 지정
pd.DataFrame(data, columns=['year', 'state', 'pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [62]:
# 사전에 없는 값은 결측치로 저장

frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                     index = ['one', 'two', 'three', 'four', 'five', 'six'])

In [63]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [64]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [65]:
# DataFrame의 열은 사전형식 표기법이나 속성 형식으로 접근 가능

frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [66]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [67]:
# 반환된 Series객체가 DataFrame과 같은 색인을 가지면 name 속성이 채워진다.

frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [68]:
# 열은 대입가능
# 현재 비어있는 'debt' 컬럼에 스칼라값이나 배열의 값으 넣어보자.

frame2['debt'] = 16.5

In [69]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [70]:
frame2['debt'] = np.arange(6.)

In [71]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [72]:
# 리스트나 배열을 컬럼에 대입할 때는 대입하려는 값의 길이가 DataFrame의 크기와 동일해야한다.
# Series를 대입하면 DataFrame의 색인에 따라 값이 대입되며 존재하지 않는 색인에는 결측치가 대입된다.

val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])

In [73]:
frame2['debt'] = val

In [74]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [75]:
# 존재하지 않는 컬럼을 대입하면 새로운 컬럼을 생성한다.
# 파이썬 사전형에서처럼 del 예약어를 사용해서 컬럼을 삭제할 수 있다.

# state 컬럼의 값이 'Ohio'인지 아닌지에 대한 불리언 값을 갖는 새로운 컬럼 생성
frame2['eastern'] = frame2.state == 'Ohio'

In [76]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [77]:
# del 예약어로 이 컬럼 삭제

del frame2['eastern']

In [78]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [104]:
# 중첩된 사전을 이용해 데이터 생성가능

pop = {'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6},
      'Nevada': {2001: 2.4, 2002: 2.9}}

In [105]:
# 이 중첩된 사전을 DataFrame에 넘기면 밖에 있는 사전의 키는 컬럼이 되고 안에 있는 키는 로우가 된다.

frame3 = pd.DataFrame(pop)

In [106]:
frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [107]:
# Numpy 배열과 유사하게 데이터를 전치할 수 있다.

frame3.T

2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [83]:
# 중첩된 사전을 이용해 DataFrame을 생성할 때 안에 있는 사전값은 키값별로 조합되어 색인이 되지만
# 직접 색인을 지정할 수 있다.

pd.DataFrame(pop, index=[2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [84]:
# Series 객체를 담고 있는 사전 데이터도 같은 방식으로 취급된다.

pdata = {'Ohio': frame3['Ohio'][:-1],
        'Nevada': frame3['Nevada'][:2]}

In [85]:
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [86]:
frame3.index.name = 'year'; frame3.columns.name = 'state'

In [87]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [88]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [89]:
# DataFrame 컬럼이 서로 다른 dtype을 갖고 있다면 모든 컬럼을 수용하기 위해 그 컬럼 배열의 dtype이 선택된다.

frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [90]:
##### 5.1.3 색인 객체 #####
# 색인객체 : pandas의 색인 객체는 표 형식의 데이터에서 각 행과 열에 대한 이름과 다른 메타데이터를 저장하는 객체

In [91]:
import pandas as pd
import numpy as np

In [92]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])

In [93]:
index = obj.index

In [94]:
index

Index(['a', 'b', 'c'], dtype='object')

In [95]:
index[1:]

Index(['b', 'c'], dtype='object')

In [96]:
# 색인 객체는 변경이 불가능하다.

index[1] = 'd'

TypeError: Index does not support mutable operations

In [97]:
# 그러므로 자료구조 사이에서 안전하게 공유될 수 있다.

labels = pd.Index(np.arange(3))

In [98]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [99]:
obj2 = pd.Series([1.5, -2.5, 0], index = labels)

In [100]:
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [101]:
obj2.index is labels

True

In [108]:
# index의 객체도 고정 크기로 동작한다.

frame3

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [109]:
frame3.columns

Index(['Ohio', 'Nevada'], dtype='object')

In [110]:
'Ohio' in frame3.columns

True

In [111]:
2003 in frame3.index

False

In [112]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])

In [113]:
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')